[profile.default]
via_ir = true
optimizer = true
optimizer_runs = 200


solc_version = "0.8.19"
src = "src"
out = "out"
libs = ["lib"]
test = "test"
remappings = [
    '@openzeppelin=lib/openzeppelin-contracts',
    '@uniswap/v3-core=lib/v3-core',
    '@uniswap/v3-periphery=lib/v3-periphery',
    '@flare-smart-contracts=lib/flare-periphery-contracts',

]
